name = "Busbar_splitting_metrics"
uuid = "c9884585-5b09-4ff3-881e-34974e198105"
authors = ["Giacomo Bastianel"]
version = "1.0.0-DEV"

[deps]
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
